name: "Hello Actions"
description: "Greet someone"
author: "octocat@github.com"

inputs:
  my-name:
    description: "Who to greet"
    required: true
    default: "World"

runs:
  using: "composite"
  steps:
    - id: run-bash
      env:
        INPUT_MY_NAME: ${{ inputs.my-name }}
      run: ${{ github.action_path }}/entrypoint.sh
      shell: bash
