name: A workflow for my Hello World file
on: push
jobs:
  general: # this is a job ID
    name: general lists.
    runs-on: ubuntu-latest
    steps:
      - name: Import an external action
        uses: actions/checkout@v1
      - name: Import a action.yml from sub dir.
        uses: ./action-a
        with:
          my-name: "Mona"
      - name: run arbitrary bash command.
        env:
          MY_VAR: Hi there! My name is
          FIRST_NAME: Lisa
          MIDDLE_NAME: The
          LAST_NAME: Octocat
        run: |
          echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.
  variable-list:
    name: Lists of variables avialable in the action.
    runs-on: ubuntu-latest
      steps:
        - name: job variables.
          run: |
            echo ${{ job.general }}