name: Workflow just to document how actions work.
on: push #https://docs.github.com/en/actions/reference/events-that-trigger-workflows
jobs:
  general: # this is a job ID
    name: How actions and scripts work
    runs-on: ubuntu-latest
    steps:
      - name: Import an external action
        uses: actions/checkout@v1
      - name: Import a action.yml from sub dir. And set it's variable
        uses: ./action-a
        with:
          my-name: "Mona"
      - name: run arbitrary bash command.
        env:
          MY_VAR: Hi there! My name is
          FIRST_NAME: Lisa
          MIDDLE_NAME: The
          LAST_NAME: Octocat
        run: |
          echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.
      - name: run bash script.
        env:
          VAR_1: This will be echoed.
        run: ${{ github.workspace }}/workflow.sh
        shell: bash
  # https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#example-printing-context-information-to-the-log-file
  all-vars:
    name: all variables.
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJSON(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJSON(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJSON(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJSON(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJSON(matrix) }}
        run: echo "$MATRIX_CONTEXT"
  # https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions
  relevant-vars:
    name: Variables I find usefull..
    runs-on: ubuntu-latest
    steps:
      - name: github.job
        run: |
          echo ${{ github.job }}
      - name: github.repositoryUrl
        run: |
          echo ${{ github.repositoryUrl }}
      - name: github.event_name (event that triggered this action "push")
        run: |
          echo ${{ github.event_name }}
      - name: github.sha commit hash
        run: |
          echo ${{ github.sha }}
      - name: github.ref The branch or tag ref that triggered the workflow run  refs/heads/BRANCHNAME or refs/tags/TAGNAME
        run: |
          echo ${{ github.ref }}
      - name: github.head_ref  Source branch of the PR. Only when 'on' is pull_request or pull_request_target.
        run: |
          echo ${{ github.head_ref }}
      - name: github.base_ref  Target branch of the PR. Only when 'on' is pull_request or pull_request_target.
        run: |
          echo ${{ github.base_ref }}
      - name: github.workspace Path to repo
        run: |
          echo ${{ github.workspace }}
      - name: github.workflow Name of this workflow (see line 1)
        run: |
          echo ${{ github.workflow }}
# https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#functions
# functions
